# http://www.appveyor.com/docs/appveyor-yml
environment:
  nodejs_version: '12.6.0'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

cache:
  - node_modules -> package.json

version: "{build}"
build: off
deploy: off
os: Visual Studio 2019
platform: x64
matrix:
  fast_finish: true
